### ISSUE TITLE
Incorporate Eye Tracking file into dataset

### ISSUE THREAD

**Issue by jstout211** [nih-megcore/nih_to_mne#21]
https://mne.tools/dev/generated/mne.preprocessing.realign_raw.html

**Comment by LinaTeichmann1** [comment]
- [ ] get rid of trailing zeros in the raw meg file
- [ ] further cleanup (add comments)
- [ ] make command line callable
